server:
  port: 8088
api:
  prefix: v1/api
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/app
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: admin123
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
file_storage:
  device_image: uploads/devices
  room_image: uploads/rooms
jwt:
  expiration: 2592000
  secretKey: ajJ1OjmhtqSEcDaJqQ7yKMxV66ybyO0SKvS0JlWDLsQ=
